[package]
name = "payload-validator"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[profile.release]
strip = "symbols"
opt-level = 3

[dependencies]
oas3 = "0.16.1"
jsonschema = "0.30.0"
serde_json = "1.0.140"
once_cell = "1.21.3"
dashmap = "7.0.0-rc2"
serde = { version = "1.0.219", features = ["derive"] }
http = "1.3.1"

#[dev-dependencies]
#criterion = "0.5.1"
#
#[[bench]]
#name = "validate_benchmarks"
#harness = false


